### ISSUE TITLE
[minor] manuscript typo line 70

### ISSUE THREAD

**Issue by govarguz** [jorisparet/partycls#10]
In the Ms. line 70:

"This is easily achieved even with a simple radial descriptor, since **that** the average radial distribution of particles at the boundaries is different than the one of the crystal in the bulk."

shall read:

"This is easily achieved even with a simple radial descriptor, since the average radial distribution of particles at the boundaries is different than the one of the crystal in the bulk."

**Comment by jorisparet** [comment]
This is now fixed, thank you for raising this issue.
