### ISSUE TITLE
[backend] Ovito support?

### ISSUE THREAD

**Issue by FTurci** [jorisparet/partycls#3]
Running the snippet present in the README.md 
```
from partycls import Trajectory, Workflow

traj = Trajectory('partycls/data/dislocation.xyz')
wf = Workflow(traj, descriptor='ba', clustering='kmeans')
wf.run()
traj[0].show(color='label', backend='ovito')
```

returns an error

```ValueError: unknown backend for visualization```

**Comment by jorisparet** [comment]
Hi Francesco,

I assume you installed the package via pypi? The support for Ovito was added here _after_ the first upload on pypi so the versions on GitHub and pypi slightly differ. I will increment the version to 1.1.0 and push it to pypi to account for the latest changes on the repo.

Thank you for raising this issue.
