### ISSUE TITLE
[testing] pytest issue with Fortran module?

### ISSUE THREAD

**Issue by FTurci** [jorisparet/partycls#4]
Something odd with the tests: Running `pytest` in the `test` folder returns 
```E   ModuleNotFoundError: No module named 'partycls.descriptor.realspace_wrap'```

Should I run a specific command for the test to include the Fortran module that `realspace_wrap` refers to? If so, this should be documented.

**Comment by FTurci** [comment]
The only working route seems to be to pre-compile the fortran module with 

```
cd partycls/descriptor 
f2py -c -m realspace_wrap realspace.f90 

```

and the execute the tests. I suggest to add this information to the documentation (fore example, the README).

**Comment by jorisparet** [comment]
Absolutely, the Fortran module should be compiled prior to running the tests. I will add a note to the README. Thanks!
